### ISSUE TITLE
Tracker Component

### ISSUE THREAD

**Issue by ntrappe** [ntrappe/cse112-s22-group2#27]
**Custom Component**: <tracker>

This component should have:
- [x] heading that contains the question we are tracking
- [x] some centered holder that will contain the response
- [x] some number/emoji inside the holder
- [x] some instruction of how to interact below the holder
- [x] buttons on the left/right bottom half to continue to next or go to previous
- [x] if user taps on number/emoji in holder, they should be able to type in something new
- [x] parse the input to make sure it's allowed (i.e. if we want hours of sleep, must be a number between 0 and 24; if we want an emoji, check that range, etc.)
- [ ] each tracker will be appended + displayed on `trackers.html`

Overall structure:
<img width="397" alt="Screen Shot 2022-05-26 at 9 47 56 PM" src="https://user-images.githubusercontent.com/33298966/170631134-7bc40f07-3053-4209-b291-39fc53c6a2b8.png">

Styling Examples:
(You can look at the [Figma](https://www.figma.com/file/J87cj9HiQVI8xtOvtBREtT/CSE-112-Prototypes?node-id=0%3A1) for more)
<img width="513" alt="Screen Shot 2022-05-26 at 9 48 27 PM" src="https://user-images.githubusercontent.com/33298966/170631207-f458a612-36a3-4fa3-9d08-2f279b40e33e.png">
